package com.alekss.toolkit;

import android.app.*;
import android.os.*;
import android.content.*;
import android.net.Uri;
import android.provider.OpenableColumns;
import android.graphics.*;
import android.view.*;
import android.widget.*;
import java.io.*;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.util.*;
import java.util.concurrent.*;
import java.util.zip.*;
import jadx.api.*;

public class MainActivity extends Activity {
    static final int PICK=1001, SAVE=1002;
    static final int BG=Color.rgb(7,17,31), PANEL=Color.rgb(11,23,39), PANEL2=Color.rgb(14,29,49);
    static final int CYAN=Color.rgb(82,217,255), TEXT=Color.rgb(216,233,247), MUTED=Color.rgb(120,147,170), GREEN=Color.rgb(73,209,125), RED=Color.rgb(255,95,95);
    LinearLayout explorer; TextView title,info,status,stats,lines; EditText editor;
    File file; String name=""; boolean textFile; final ExecutorService pool=Executors.newSingleThreadExecutor();

    @Override public void onCreate(Bundle b){super.onCreate(b); getWindow().setStatusBarColor(Color.rgb(5,11,19)); getWindow().setNavigationBarColor(Color.rgb(5,11,19)); ui();}
    @Override protected void onDestroy(){pool.shutdownNow();super.onDestroy();}

    void ui(){
        LinearLayout root=col(BG); LinearLayout top=row(PANEL); top.setPadding(dp(10),0,dp(10),0);
        TextView logo=t("â",25,CYAN); top.addView(logo,lp(42,58));
        LinearLayout brand=col(Color.TRANSPARENT); TextView a=t("ALEKS SOFT",10,CYAN); a.setTypeface(null,Typeface.BOLD); TextView d=t("DecoderPRO",20,TEXT); d.setTypeface(null,Typeface.BOLD); brand.addView(a);brand.addView(d);brand.addView(t("Reverse Engineering â¢ Decompiler â¢ Crypto â¢ Analyzer",8,MUTED)); top.addView(brand,wlp(1,58));
        Button o=btn("OPEN");o.setOnClickListener(v->open());top.addView(o,lp(80,42)); Button s=btn("SAVE");s.setOnClickListener(v->save());top.addView(s,lp(80,42)); root.addView(top,lp(-1,64));
        LinearLayout work=row(BG);
        LinearLayout left=col(PANEL); for(String n:new String[]{"EXPLORER","SEARCH","ANALYSIS","CRYPTO","COMPRESS","RE TOOLS","SETTINGS","ABOUT"}){TextView x=t(n,11,n.equals("EXPLORER")?CYAN:MUTED);x.setPadding(dp(10),dp(8),0,dp(8));x.setOnClickListener(v->nav(n));left.addView(x);} left.addView(t("PROJECT EXPLORER",10,MUTED)); ScrollView es=new ScrollView(this);explorer=col(Color.TRANSPARENT);explorer.addView(t("ð No file open\n\nPress OPEN.",10,MUTED));es.addView(explorer);left.addView(es,wlp(1,0));work.addView(left,wlp(.20f,0));
        LinearLayout center=col(BG); LinearLayout tabs=row(PANEL);title=t("  NO FILE OPEN",11,CYAN);tabs.addView(title,wlp(1,38));TextView close=t("Ã",22,MUTED);close.setGravity(Gravity.CENTER);close.setOnClickListener(v->closeFile());tabs.addView(close,lp(44,38));center.addView(tabs);
        LinearLayout bar=row(PANEL2); for(String n:new String[]{"HEX","STRINGS","HASH","INFO"}){Button b=small(n);b.setOnClickListener(v->{if(n.equals("HEX"))hexView();else if(n.equals("STRINGS"))stringsView();else if(n.equals("HASH"))hashView();else infoView();});bar.addView(b,lp(78,34));}center.addView(bar);
        LinearLayout code=row(BG);lines=t("1",11,MUTED);lines.setTypeface(Typeface.MONOSPACE);lines.setGravity(Gravity.TOP|Gravity.RIGHT);code.addView(lines,lp(45,-1));editor=new EditText(this);editor.setTextColor(TEXT);editor.setHintTextColor(MUTED);editor.setHint("Open a file to analyze it...");editor.setTextSize(12);editor.setTypeface(Typeface.MONOSPACE);editor.setGravity(Gravity.TOP);editor.setBackgroundColor(BG);editor.setSingleLine(false);editor.setHorizontallyScrolling(true);editor.addTextChangedListener(new android.text.TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){lineNums();}public void afterTextChanged(android.text.Editable e){}});code.addView(editor,wlp(1,0));ScrollView cs=new ScrollView(this);cs.addView(code);center.addView(cs,wlp(1,0));work.addView(center,wlp(.50f,0));
        LinearLayout right=col(PANEL);ScrollView rs=new ScrollView(this);LinearLayout rc=col(Color.TRANSPARENT);rc.setPadding(dp(8),dp(8),dp(8),dp(8));rc.addView(t("FILE ANALYSIS",12,CYAN));info=t("Type: â\nName: â\nSize: â\nSHA-256: â",10,TEXT);info.setPadding(dp(8),dp(8),0,dp(8));info.setBackgroundColor(PANEL2);rc.addView(info);for(String[] x:new String[][]{{"DECOMPILE","d"},{"HEX VIEW","h"},{"STRINGS","s"},{"HASH","ha"},{"INFO","i"}}){Button b=btn(x[0]);b.setOnClickListener(v->act(x[1]));rc.addView(b,lp(-1,36));}section(rc,"DECOMPILATION");stats=t("Classes: â\nMethods: â\nFields: â\nStatus: Ready",10,TEXT);rc.addView(stats);section(rc,"CRYPTO / ENCODING");rc.addView(t("AES â¢ RSA â¢ SM4 â¢ HMAC\nSHA-256 â¢ SHA-1 â¢ MD5\nBase64 â¢ Hex\nUser-provided keys/parameters.",9,MUTED));section(rc,"COMPRESSION");rc.addView(t("ZIP â¢ zlib â¢ zstd â¢ LZ4\nArchive inspection.",9,MUTED));section(rc,"RE TOOLS");rc.addView(t("ELF / ARM64 local analysis\nGhidra / IDA external workflow\nrizin / radare2 external workflow\nx64dbg / WinDbg Windows only\nFrida authorized runtime integration",9,MUTED));section(rc,"PAK");rc.addView(t("Header â¢ Index â¢ Entries\nCompression/encryption metadata\nUser-provided key/IV workflow",9,MUTED));rs.addView(rc);right.addView(rs,wlp(1,0));work.addView(right,wlp(.30f,0));root.addView(work,wlp(1,0));
        LinearLayout bottom=row(Color.rgb(5,13,24));bottom.addView(t("TERMINAL   BUILD   LOGCAT   PROBLEMS   SEARCH RESULTS",9,MUTED),wlp(1,42));status=t("â READY",10,GREEN);bottom.addView(status,lp(130,42));root.addView(bottom,lp(-1,42));setContentView(root);
    }

    void open(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("*/*");startActivityForResult(i,PICK);}
    @Override protected void onActivityResult(int r,int c,Intent d){super.onActivityResult(r,c,d);if(r==PICK&&c==RESULT_OK&&d!=null&&d.getData()!=null)loadUri(d.getData());if(r==SAVE&&c==RESULT_OK&&d!=null&&d.getData()!=null)writeUri(d.getData());}
    void loadUri(Uri u){setStatus("â OPENING...",CYAN);pool.execute(()->{try{String n=display(u);if(n==null)n="selected_file";File f=new File(getCacheDir(),"dp_"+System.currentTimeMillis()+"_"+n.replaceAll("[^A-Za-z0-9._-]","_"));try(InputStream in=getContentResolver().openInputStream(u);OutputStream out=new FileOutputStream(f)){if(in==null)throw new IOException("Cannot open file");byte[] b=new byte[65536];int z;while((z=in.read(b))!=-1)out.write(b,0,z);}file=f;name=n;runOnUiThread(()->analyze());}catch(Exception e){runOnUiThread(()->err(e));}});}
    void analyze(){title.setText("  "+name);textFile=isText(name);updateExplorer();pool.execute(()->{try{String type=type(read(f,64),name),sha=digest("SHA-256"),ent=String.format(Locale.US,"%.4f",entropy());String out="Type: "+type+"\nName: "+name+"\nSize: "+size(f.length())+"\nSHA-256: "+sha+"\nEntropy: "+ent;String txt=textFile?readText():"";runOnUiThread(()->{info.setText(out);if(textFile)editor.setText(txt);else editor.setText("");if(isZip(type))zipTree();setStatus("â PROJECT OPEN",GREEN);});}catch(Exception e){runOnUiThread(()->err(e));}});}
    void updateExplorer(){explorer.removeAllViews();explorer.addView(t("ð¦ "+name,11,CYAN));explorer.addView(t("Type: "+typeSafe(),9,MUTED));}
    void zipTree(){pool.execute(()->{ArrayList<String> a=new ArrayList<>();try(ZipFile z=new ZipFile(file)){Enumeration<? extends ZipEntry> e=z.entries();while(e.hasMoreElements()&&a.size()<1500){ZipEntry x=e.nextElement();a.add((x.isDirectory()?"ð ":"ð ")+x.getName()+(x.isDirectory()?"":"  ["+size(x.getSize())+"]"));}}catch(Exception e){a.add("ERROR: "+e.getMessage());}runOnUiThread(()->{explorer.removeAllViews();explorer.addView(t("ð¦ "+name,11,CYAN));for(String x:a){TextView v=t(x,9,TEXT);v.setPadding(dp(6),dp(3),0,dp(3));explorer.addView(v);}});});}
    void act(String x){if(x.equals("d"))decompile();else if(x.equals("h"))hexView();else if(x.equals("s"))stringsView();else if(x.equals("ha"))hashView();else infoView();}
    void hexView(){if(!ok())return;pool.execute(()->{try{String s=hexDump(read(f,8192));runOnUiThread(()->setEditor("HEX: "+name,s));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void stringsView(){if(!ok())return;pool.execute(()->{try{String s=strings(1000);runOnUiThread(()->setEditor("STRINGS: "+name,s));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void hashView(){if(!ok())return;pool.execute(()->{try{String s="MD5     "+digest("MD5")+"\nSHA-1   "+digest("SHA-1")+"\nSHA-256 "+digest("SHA-256");runOnUiThread(()->setEditor("HASH: "+name,s));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void infoView(){if(!ok())return;pool.execute(()->{try{String s="Name: "+name+"\nType: "+typeSafe()+"\nSize: "+size(f.length())+"\nModified: "+new Date(f.lastModified())+"\nEntropy: "+entropy();runOnUiThread(()->setEditor("INFO: "+name,s));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void decompile(){if(!ok())return;String n=name.toLowerCase(Locale.US);if(!(n.endsWith(".apk")||n.endsWith(".dex")||n.endsWith(".jar")||n.endsWith(".class"))){show("JADX input: APK / DEX / JAR / CLASS. Selected: "+name);return;}setStatus("â DECOMPILING...",CYAN);pool.execute(()->{try{JadxArgs a=new JadxArgs();a.setInputFile(f);a.setOutDir(new File(getCacheDir(),"jadx_"+System.currentTimeMillis()));StringBuilder s=new StringBuilder();int c=0,m=0,fl=0;try(JadxDecompiler j=new JadxDecompiler(a)){j.load();for(JavaClass x:j.getClasses()){c++;m+=x.getMethods().size();fl+=x.getFields().size();s.append("// ").append(x.getFullName()).append("\n").append(x.getCode()).append("\n\n");if(c>=80){s.append("// Mobile output limit: 80 classes\n");break;}}}int cc=c,mm=m,ff=fl;runOnUiThread(()->{stats.setText("Classes: "+cc+"\nMethods: "+mm+"\nFields: "+ff+"\nStatus: Complete");setEditor("DECOMPILED: "+name,s.toString());setStatus("â READY",GREEN);});}catch(Exception e){runOnUiThread(()->err(e));}});}
    void save(){if(editor.getText().length()==0){show("Nothing to save.");return;}Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/plain");i.putExtra(Intent.EXTRA_TITLE,name.length()>0?name:"decoded.txt");startActivityForResult(i,SAVE);}
    void writeUri(Uri u){pool.execute(()->{try(OutputStream o=getContentResolver().openOutputStream(u)){if(o==null)throw new IOException("Cannot open destination");o.write(editor.getText().toString().getBytes(StandardCharsets.UTF_8));runOnUiThread(()->setStatus("â SAVED",GREEN));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void search(String q){if(!ok()||q.trim().isEmpty())return;pool.execute(()->{try{String s=textFile?readText():strings(2000),l=s.toLowerCase(Locale.US),n=q.toLowerCase(Locale.US);StringBuilder o=new StringBuilder();int p=0,h=0;while((p=l.indexOf(n,p))>=0&&h<100){int a=l.lastIndexOf('\n',p)+1,b=l.indexOf('\n',p);if(b<0)b=s.length();o.append(s,a,b).append('\n');h++;p+=Math.max(1,n.length());}String r=h==0?"No matches.":"Matches: "+h+"\n\n"+o;runOnUiThread(()->setEditor("SEARCH: "+q,r));}catch(Exception e){runOnUiThread(()->err(e));}});}
    void nav(String n){if(n.equals("SEARCH")){EditText q=new EditText(this);q.setHint("Search current file");new AlertDialog.Builder(this).setTitle("SEARCH").setView(q).setPositiveButton("SEARCH",(d,w)->search(q.getText().toString())).setNegativeButton("CANCEL",null).show();}else if(n.equals("ANALYSIS"))show("HEX â¢ STRINGS â¢ HASH â¢ ENTROPY â¢ TYPE DETECTION");else if(n.equals("CRYPTO"))show("AES â¢ RSA â¢ SM4 â¢ HMAC â¢ SHA â¢ Base64 â¢ Hex\n\nDecryption requires the correct user-provided parameters.");else if(n.equals("COMPRESS"))show("ZIP â¢ zlib â¢ zstd â¢ LZ4");else if(n.equals("RE TOOLS"))show("Local ELF/ARM64 analysis; Ghidra/IDA and Windows debuggers are external integrations.");else show("ALEKS SOFT DecoderPRO\nVersion 1.1.0");}
    boolean ok(){if(file==null||!file.exists()){show("Open a file first.");return false;}return true;}
    void closeFile(){file=null;name="";editor.setText("");title.setText("  NO FILE OPEN");info.setText("Type: â\nName: â\nSize: â\nSHA-256: â");stats.setText("Classes: â\nMethods: â\nFields: â\nStatus: Ready");explorer.removeAllViews();explorer.addView(t("ð No file open\n\nPress OPEN.",10,MUTED));setStatus("â READY",GREEN);}
    void setEditor(String ti,String s){title.setText("  "+ti);editor.setText(s);editor.setSelection(0);lineNums();}
    void lineNums(){if(lines==null)return;String s=editor.getText().toString();int n=1;for(int i=0;i<s.length();i++)if(s.charAt(i)=='\n')n++;StringBuilder b=new StringBuilder();for(int i=1;i<=n;i++)b.append(i).append('\n');lines.setText(b.toString());}
    String display(Uri u){try(android.database.Cursor c=getContentResolver().query(u,new String[]{OpenableColumns.DISPLAY_NAME},null,null,null)){if(c!=null&&c.moveToFirst())return c.getString(0);}catch(Exception ignored){}return null;}
    byte[] read(File x,int max)throws IOException{try(InputStream i=new BufferedInputStream(new FileInputStream(x))){ByteArrayOutputStream o=new ByteArrayOutputStream();byte[] b=new byte[4096];int z,total=0;while(total<max&&(z=i.read(b,0,Math.min(b.length,max-total)))>0){o.write(b,0,z);total+=z;}return o.toByteArray();}}
    String readText()throws IOException{return new String(read(file,2*1024*1024),StandardCharsets.UTF_8);}
    String digest(String alg)throws Exception{MessageDigest d=MessageDigest.getInstance(alg);try(InputStream i=new BufferedInputStream(new FileInputStream(file))){byte[] b=new byte[65536];int n;while((n=i.read(b))!=-1)d.update(b,0,n);}return hex(d.digest());}
    double entropy()throws IOException{long[] f=new long[256];long total=0;try(InputStream i=new BufferedInputStream(new FileInputStream(file))){byte[] b=new byte[65536];int n;while((n=i.read(b))!=-1){for(int j=0;j<n;j++){f[b[j]&255]++;total++;}}}double e=0;for(long x:f)if(x>0){double p=(double)x/total;e-=p*(Math.log(p)/Math.log(2));}return e;}
    String strings(int max)throws IOException{StringBuilder o=new StringBuilder(),c=new StringBuilder();int found=0;try(InputStream i=new BufferedInputStream(new FileInputStream(file))){byte[] b=new byte[65536];int n;while((n=i.read(b))!=-1&&found<max)for(int j=0;j<n&&found<max;j++){int x=b[j]&255;if(x>=32&&x<=126)c.append((char)x);else{if(c.length()>=4){o.append(c).append('\n');found++;}c.setLength(0);}}}if(c.length()>=4&&found<max)o.append(c).append('\n');return o.length()==0?"(no printable strings found)":o.toString();}
    String hexDump(byte[] b){StringBuilder o=new StringBuilder();for(int i=0;i<b.length;i+=16){o.append(String.format(Locale.US,"%08X  ",i));for(int j=0;j<16;j++)o.append(i+j<b.length?String.format(Locale.US,"%02X ",b[i+j]&255):"   ");o.append(" | ");for(int j=0;j<16&&i+j<b.length;j++){int x=b[i+j]&255;o.append(x>=32&&x<=126?(char)x:'.');}o.append('\n');}return o.toString();}
    String hex(byte[] b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format(Locale.US,"%02x",x&255));return s.toString();}
    String typeSafe(){try{return type(read(file,64),name);}catch(Exception e){return "Unknown";}}
    String type(byte[] b,String n){String x=n.toLowerCase(Locale.US);if(b.length>=4&&(b[0]&255)==127&&b[1]=='E'&&b[2]=='L'&&b[3]=='F')return "ELF";if(b.length>=4&&b[0]=='d'&&b[1]=='e'&&b[2]=='x'&&b[3]==10)return "DEX";if(b.length>=4&&b[0]=='P'&&b[1]=='K'){if(x.endsWith(".apk"))return "APK / ZIP";if(x.endsWith(".aab"))return "AAB / ZIP";if(x.endsWith(".aar"))return "AAR / ZIP";if(x.endsWith(".jar"))return "JAR / ZIP";return "ZIP";}if(x.endsWith(".class"))return "Java CLASS";if(x.endsWith(".pak"))return "PAK candidate";if(x.endsWith(".so"))return "Native ELF candidate";return "Binary / Data";}
    boolean isZip(String x){return x.contains("ZIP")||x.contains("APK")||x.contains("AAB")||x.contains("AAR")||x.contains("JAR");}
    boolean isText(String x){String n=x.toLowerCase(Locale.US);for(String e:new String[]{".txt",".md",".java",".kt",".xml",".json",".gradle",".properties",".smali",".c",".h",".cpp",".hpp",".cs",".go",".rs",".py",".js",".ts",".html",".css",".sh",".yaml",".yml",".ini",".cfg",".toml"})if(n.endsWith(e))return true;return false;}
    String size(long x){if(x<1024)return x+" B";if(x<1048576)return String.format(Locale.US,"%.2f KB",x/1024.0);if(x<1073741824)return String.format(Locale.US,"%.2f MB",x/1048576.0);return String.format(Locale.US,"%.2f GB",x/1073741824.0);}
    void section(LinearLayout p,String s){TextView x=t(s,11,CYAN);x.setTypeface(null,Typeface.BOLD);x.setPadding(0,dp(10),0,dp(4));p.addView(x);}
    TextView t(String s,float z,int c){TextView x=new TextView(this);x.setText(s);x.setTextSize(z);x.setTextColor(c);return x;}
    Button btn(String s){Button b=new Button(this);b.setText(s);b.setTextColor(TEXT);b.setTextSize(10);b.setAllCaps(false);b.setBackgroundColor(PANEL2);return b;}
    Button small(String s){return btn(s);}
    LinearLayout row(int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.HORIZONTAL);x.setGravity(Gravity.CENTER_VERTICAL);x.setBackgroundColor(c);return x;}
    LinearLayout col(int c){LinearLayout x=new LinearLayout(this);x.setOrientation(LinearLayout.VERTICAL);x.setBackgroundColor(c);return x;}
    LinearLayout.LayoutParams lp(int w,int h){return new LinearLayout.LayoutParams(w<0?w:dp(w),h<0?h:dp(h));}
    LinearLayout.LayoutParams wlp(float w,int h){return new LinearLayout.LayoutParams(0,h<0?LinearLayout.LayoutParams.MATCH_PARENT:dp(h),w);}
    int dp(int x){return Math.round(x*getResources().getDisplayMetrics().density);}
    void setStatus(String s,int c){status.setText(s);status.setTextColor(c);}
    void show(String s){new AlertDialog.Builder(this).setTitle("Aleks Soft DecoderPRO").setMessage(s).setPositiveButton("OK",null).show();}
    void err(Exception e){setStatus("â ERROR",RED);show(e.getClass().getSimpleName()+": "+String.valueOf(e.getMessage()));}
